// Copyright 2020 Orijtech, Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package structslop

// Size classes copied from runtime/sizeclasses.go, generated by
// runtime/mksizeclasses.go. They have been stable across Go releases; if a
// future release changes them, the numbers here only affect reported sizes.
const (
	maxSmallSize = 32768
	pageSize     = 8192
)

var classToSize = [...]uintptr{
	0, 8, 16, 24, 32, 48, 64, 80, 96, 112, 128, 144, 160, 176, 192, 208, 224,
	240, 256, 288, 320, 352, 384, 416, 448, 480, 512, 576, 640, 704, 768, 896,
	1024, 1152, 1280, 1408, 1536, 1792, 2048, 2304, 2688, 3072, 3200, 3456,
	4096, 4864, 5376, 6144, 6528, 6784, 6912, 8192, 9472, 9728, 10240, 10880,
	12288, 13568, 14336, 16384, 18432, 19072, 20480, 21760, 24576, 27264,
	28672, 32768,
}

// roundUpSize returns the size of the memory block that the runtime allocates
// for an object of the given size. It mirrors runtime.roundupsize, which
// cannot be linknamed since Go 1.23.
func roundUpSize(size uintptr) uintptr {
	if size < maxSmallSize {
		for _, s := range classToSize {
			if size <= s {
				return s
			}
		}
	}
	// Large object: round up to the next page, unless that overflows.
	if size+pageSize-1 < size {
		return size
	}
	return (size + pageSize - 1) &^ (pageSize - 1)
}
